Portfolio: desktop version
Loltolo-Lesapiti/Portfolio-desktop-version pull request #1
Opened 2022-05-06 12:28 UTC by Loltolo-Lesapiti

## This is a simple portfolio website project in the desktop version.
## On this project, I implemented the following.

- Added a contact form
- Added various job description cards.
- Added the introduction page and 
- About myself page

2022-05-06 14:41 UTC, Ismailco requested changes
### Hi @Loltolo-Lesapiti,

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-06 14:41 UTC, Ismailco commented on index.html
> +        </ul>
- [ ] The navigation items should be links that target the proper section, please fix it, so this will meet the requirements.

2022-05-06 14:41 UTC, Ismailco commented on index.html
> +    <section class="main-content">
- [ ] The Headline section needs some modification to be like the Figma design, please fix this

- Figma design:
![Screenshot_20220506_142339](https://user-images.githubusercontent.com/25227022/167152727-532dc8a9-adce-4c8a-af16-d083705b1656.png)

- Your design
![Screenshot_20220506_142542](https://user-images.githubusercontent.com/25227022/167152831-acad937e-01a4-40d1-bdda-2b911d3baadf.png)

2022-05-06 14:41 UTC, Ismailco commented on index.html
> +        <div class="card">
- [ ] Your design is not similar to the provided one, please stick as much as possible to the Figma design

-Your design:
![Screenshot_20220506_142852](https://user-images.githubusercontent.com/25227022/167153777-9e62001e-fc83-4d9c-ac52-91c19a6281ce.png)

-Figma design:
![Screenshot_20220506_143123](https://user-images.githubusercontent.com/25227022/167153884-a6181dbb-1194-4384-a6b6-e96f5edf692e.png)

2022-05-06 14:41 UTC, Ismailco commented on index.html
> +        <section class="contact-form">
- [ ] Your design needs some modification, please add some ``` border-radius ``` to the top of this section so your design can be similar to the Figma one
- [ ] [optional] You can reduce the form width, so your design can be more accurate 

-Figme design:
![Screenshot_20220506_143508](https://user-images.githubusercontent.com/25227022/167154525-3e4c7d1f-39cf-47f0-9beb-ad8ce44367e0.png)

-Your design:
![Screenshot_20220506_143206](https://user-images.githubusercontent.com/25227022/167154754-065fbb18-3c70-4b1a-8a3d-0950a6be4014.png)

2022-05-06 14:41 UTC, Ismailco commented on index.html
> +                <button type="submit" class="btn">Get it Touch</button>
- [ ] The elements of the form need to be centered including the ``` Get in Touch``` button, please fix this

2022-05-06 19:39 UTC, Loltolo-Lesapiti commented
@Ismailco.  Kindly check now. I have implemented the changes. Thank you.

2022-05-06 20:49 UTC, Ismailco commented
> @Ismailco. Kindly check now. I have implemented the changes. Thank you.

@Loltolo-Lesapiti, You didn't make all the changes, consider implementing all the changes before requesting a review in the dashboard

2022-05-06 21:09 UTC, mahbubul14 requested changes
Hi @Loltolo-Lesapiti ,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

# Required Changes ♻️

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linters error.
:heavy_check_mark: Github flow used properly.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

- [ ]  Currently, your `README` file is not updated according to the project. Please update your `README` file. You can use [this template ](https://github.com/microverseinc/readme-template)for the `README` but remember to customize it to your project.

- [ ] Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-07 02:55 UTC, Loltolo-Lesapiti commented on index.html
> +    <section class="main-content">
Hi, can you please check again? I have done the changes.

2022-05-07 03:04 UTC, nicupop729 approved these changes
Hi @Loltolo-Lesapiti, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/cQNRp4QA8z7B6/giphy.gif"/>

## Highlights
 - [X] Correct GitHub flow practice :heavy_check_mark:
 - [X] Linters are passing :heavy_check_mark:
 - [X] Nice work on the aspects pointed out by previous reviewers :clap:  :heavy_check_mark:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-07 03:36 UTC, merged